from __future__ import annotations

import hashlib

import httpx

from breachlens.config import Settings
from breachlens.models import Finding

PWNED_PASSWORDS_RANGE_URL = "https://api.pwnedpasswords.com/range/{prefix}"


def sha1_upper(value: str) -> str:
    return hashlib.sha1(value.encode("utf-8")).hexdigest().upper()


async def check_password(password: str, settings: Settings) -> Finding:
    """Check Pwned Passwords without sending the password or the full hash."""
    full_hash = sha1_upper(password)
    prefix, suffix = full_hash[:5], full_hash[5:]
    headers = {
        "User-Agent": settings.user_agent,
        "Add-Padding": "true",
    }
    async with httpx.AsyncClient(timeout=settings.timeout, headers=headers) as client:
        response = await client.get(PWNED_PASSWORDS_RANGE_URL.format(prefix=prefix))
        response.raise_for_status()

    count = 0
    for line in response.text.splitlines():
        returned_suffix, _, raw_count = line.partition(":")
        if returned_suffix.upper() == suffix:
            try:
                count = int(raw_count)
            except ValueError:
                count = 0
            break

    if count > 0:
        return Finding(
            source="Have I Been Pwned - Pwned Passwords",
            category="password_exposure",
            title="Password found in compromised password corpus",
            severity="critical" if count >= 100 else "high",
            description=(
                "The supplied password appeared in a known compromised password corpus. "
                "The query used k-anonymity: only the first five SHA-1 hash characters were sent."
            ),
            evidence={"sha1_prefix": prefix, "pwned_count": count},
            recommendation="Do not reuse this password. Rotate it immediately and enable MFA where possible.",
        )

    return Finding(
        source="Have I Been Pwned - Pwned Passwords",
        category="password_exposure",
        title="Password not found in Pwned Passwords",
        severity="info",
        description=(
            "The password was not present in the returned hash range. This does not prove that it is strong; "
            "it only means this source did not report it at query time."
        ),
        evidence={"sha1_prefix": prefix, "pwned_count": 0},
        recommendation="Use long, unique passwords generated by a password manager.",
    )
